const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const products = [
  {
    name: 'Classic Oxford Shirt',
    brand: 'Raymond',
    category: 'Shirts',
    price: 1799,
    color: 'White',
    style: 'Classic',
    rating: 4.5,
    imageUrl: 'https://placehold.co/400x500/f8f8f8/333333?text=Oxford+Shirt',
    description: 'A timeless white oxford shirt crafted from premium cotton. Perfect for formal and smart-casual occasions.',
  },
  {
    name: 'Relaxed Fit Black T-Shirt',
    brand: 'H&M',
    category: 'T-Shirts',
    price: 799,
    color: 'Black',
    style: 'Casual',
    rating: 4.2,
    imageUrl: 'https://placehold.co/400x500/1a1a1a/ffffff?text=Black+Tee',
    description: 'Essential relaxed-fit black tee made from soft organic cotton. A wardrobe staple.',
  },
  {
    name: 'Straight Fit Blue Jeans',
    brand: 'Levi\'s',
    category: 'Jeans',
    price: 2499,
    color: 'Blue',
    style: 'Casual',
    rating: 4.6,
    imageUrl: 'https://placehold.co/400x500/4a6fa5/ffffff?text=Blue+Jeans',
    description: 'Classic straight-fit jeans in mid-wash blue. Comfortable stretch denim for everyday wear.',
  },
  {
    name: 'Minimal Beige Overshirt',
    brand: 'Zara',
    category: 'Jackets',
    price: 3499,
    color: 'Beige',
    style: 'Minimalist',
    rating: 4.3,
    imageUrl: 'https://placehold.co/400x500/d4c5a9/333333?text=Beige+Overshirt',
    description: 'Lightweight overshirt in neutral beige. Layer it over a tee for effortless minimal style.',
  },
  {
    name: 'Classic White Sneakers',
    brand: 'Nike',
    category: 'Sneakers',
    price: 4999,
    color: 'White',
    style: 'Casual',
    rating: 4.7,
    imageUrl: 'https://placehold.co/400x500/f5f5f5/333333?text=White+Sneakers',
    description: 'Clean white leather sneakers. Versatile enough for any outfit, any occasion.',
  },
  {
    name: 'Slim Fit Navy Chinos',
    brand: 'Allen Solly',
    category: 'Trousers',
    price: 1999,
    color: 'Navy',
    style: 'Classic',
    rating: 4.1,
    imageUrl: 'https://placehold.co/400x500/2c3e6b/ffffff?text=Navy+Chinos',
    description: 'Tailored slim-fit chinos in deep navy. Great for office or smart-casual outings.',
  },
  {
    name: 'Floral Print Summer Dress',
    brand: 'AND',
    category: 'Dresses',
    price: 2999,
    color: 'Multi',
    style: 'Casual',
    rating: 4.4,
    imageUrl: 'https://placehold.co/400x500/f0e4d7/8b6f47?text=Floral+Dress',
    description: 'Breezy floral print dress perfect for summer days. Lightweight fabric with a flattering A-line cut.',
  },
  {
    name: 'Oversized Graphic Tee',
    brand: 'Bewakoof',
    category: 'T-Shirts',
    price: 599,
    color: 'Grey',
    style: 'Gen Z Streetwear',
    rating: 4.0,
    imageUrl: 'https://placehold.co/400x500/808080/ffffff?text=Graphic+Tee',
    description: 'Trendy oversized tee with minimalist graphic print. Streetwear essential for Gen Z.',
  },
  {
    name: 'Tan Leather Loafers',
    brand: 'Clarks',
    category: 'Loafers',
    price: 4499,
    color: 'Brown',
    style: 'Classic',
    rating: 4.5,
    imageUrl: 'https://placehold.co/400x500/8B6914/ffffff?text=Tan+Loafers',
    description: 'Premium tan leather loafers with cushioned insole. Ideal for office and formal events.',
  },
  {
    name: 'Black Formal Trousers',
    brand: 'Van Heusen',
    category: 'Trousers',
    price: 1799,
    color: 'Black',
    style: 'Formal',
    rating: 4.3,
    imageUrl: 'https://placehold.co/400x500/1a1a1a/ffffff?text=Formal+Trousers',
    description: 'Sharp black formal trousers with a tailored fit. Essential for professional wardrobes.',
  },
  {
    name: 'Denim Jacket',
    brand: 'Levi\'s',
    category: 'Jackets',
    price: 3999,
    color: 'Blue',
    style: 'Casual',
    rating: 4.6,
    imageUrl: 'https://placehold.co/400x500/5b7ea1/ffffff?text=Denim+Jacket',
    description: 'Classic trucker-style denim jacket. A layering staple that never goes out of fashion.',
  },
  {
    name: 'Olive Cargo Joggers',
    brand: 'Roadster',
    category: 'Trousers',
    price: 1299,
    color: 'Green',
    style: 'Sporty',
    rating: 4.1,
    imageUrl: 'https://placehold.co/400x500/6b8e23/ffffff?text=Cargo+Joggers',
    description: 'Comfortable olive cargo joggers with utility pockets. Perfect for active and casual wear.',
  },
  {
    name: 'Striped Linen Shirt',
    brand: 'Uniqlo',
    category: 'Shirts',
    price: 1999,
    color: 'Blue',
    style: 'Minimalist',
    rating: 4.4,
    imageUrl: 'https://placehold.co/400x500/c4d4e0/333333?text=Linen+Shirt',
    description: 'Lightweight striped linen shirt for summer. Breathable fabric with relaxed tailoring.',
  },
  {
    name: 'Black Slim Fit Jeans',
    brand: 'Jack & Jones',
    category: 'Jeans',
    price: 1999,
    color: 'Black',
    style: 'Casual',
    rating: 4.3,
    imageUrl: 'https://placehold.co/400x500/1a1a1a/ffffff?text=Black+Jeans',
    description: 'Sleek black slim-fit jeans with stretch. Versatile for both casual and semi-formal looks.',
  },
  {
    name: 'Printed Silk Scarf',
    brand: 'FabIndia',
    category: 'Accessories',
    price: 1499,
    color: 'Multi',
    style: 'Classic',
    rating: 4.2,
    imageUrl: 'https://placehold.co/400x500/d4a574/ffffff?text=Silk+Scarf',
    description: 'Elegant printed silk scarf with traditional motifs. Adds sophistication to any outfit.',
  },
  {
    name: 'White Polo T-Shirt',
    brand: 'U.S. Polo',
    category: 'T-Shirts',
    price: 1299,
    color: 'White',
    style: 'Classic',
    rating: 4.3,
    imageUrl: 'https://placehold.co/400x500/f5f5f5/333333?text=Polo+Tee',
    description: 'Classic white polo with clean lines. Smart enough for the office, cool enough for weekends.',
  },
  {
    name: 'Maxi Wrap Dress',
    brand: 'Global Desi',
    category: 'Dresses',
    price: 2499,
    color: 'Maroon',
    style: 'Classic',
    rating: 4.5,
    imageUrl: 'https://placehold.co/400x500/800020/ffffff?text=Wrap+Dress',
    description: 'Flattering wrap-style maxi dress in rich maroon. Perfect for dinners and special occasions.',
  },
  {
    name: 'Bomber Jacket',
    brand: 'H&M',
    category: 'Jackets',
    price: 2999,
    color: 'Black',
    style: 'Gen Z Streetwear',
    rating: 4.4,
    imageUrl: 'https://placehold.co/400x500/1a1a1a/ffffff?text=Bomber+Jacket',
    description: 'Sleek black bomber jacket with ribbed cuffs. Essential streetwear layering piece.',
  },
  {
    name: 'Leather Belt',
    brand: 'Woodland',
    category: 'Accessories',
    price: 999,
    color: 'Brown',
    style: 'Classic',
    rating: 4.1,
    imageUrl: 'https://placehold.co/400x500/5c3317/ffffff?text=Leather+Belt',
    description: 'Genuine leather belt with brushed metal buckle. A finishing touch for any outfit.',
  },
  {
    name: 'Running Sneakers',
    brand: 'Adidas',
    category: 'Sneakers',
    price: 3999,
    color: 'Black',
    style: 'Sporty',
    rating: 4.6,
    imageUrl: 'https://placehold.co/400x500/2a2a2a/ffffff?text=Running+Shoes',
    description: 'Lightweight running sneakers with responsive cushioning. Built for performance and style.',
  },
  {
    name: 'Khaki Chino Shorts',
    brand: 'GAP',
    category: 'Trousers',
    price: 1499,
    color: 'Beige',
    style: 'Casual',
    rating: 4.0,
    imageUrl: 'https://placehold.co/400x500/c4b89a/333333?text=Chino+Shorts',
    description: 'Classic khaki chino shorts for warm weather. Clean cut with a comfortable mid-rise fit.',
  },
  {
    name: 'Ethnic Printed Kurta',
    brand: 'FabIndia',
    category: 'Shirts',
    price: 1799,
    color: 'Multi',
    style: 'Classic',
    rating: 4.3,
    imageUrl: 'https://placehold.co/400x500/d4a574/333333?text=Printed+Kurta',
    description: 'Hand-block printed cotton kurta with ethnic motifs. Perfect for festivals and casual outings.',
  },
  {
    name: 'Canvas Tote Bag',
    brand: 'Miniso',
    category: 'Accessories',
    price: 799,
    color: 'Beige',
    style: 'Minimalist',
    rating: 3.9,
    imageUrl: 'https://placehold.co/400x500/e8dcc8/333333?text=Canvas+Tote',
    description: 'Spacious canvas tote bag in natural beige. Sustainable, stylish, and everyday-ready.',
  },
  {
    name: 'High-Waist Wide Leg Pants',
    brand: 'Zara',
    category: 'Trousers',
    price: 2999,
    color: 'Black',
    style: 'Minimalist',
    rating: 4.5,
    imageUrl: 'https://placehold.co/400x500/1a1a1a/ffffff?text=Wide+Leg+Pants',
    description: 'Tailored high-waist wide-leg pants in black. Effortlessly chic for any occasion.',
  },
];

async function main() {
  console.log('🌱 Seeding database...\n');

  // Clear existing products
  await prisma.product.deleteMany();
  console.log('  Cleared existing products.');

  // Seed products
  for (const product of products) {
    await prisma.product.create({ data: product });
  }
  console.log(`  Created ${products.length} products.`);

  console.log('\n✅ Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
